### ISSUE TITLE
Could not be used in ESM environment

### ISSUE THREAD

**Issue by ankhzet** [anchan828/json-ast#1178]
The package has invalid format and can't be used from Node v20+
1. The `package.json` does not have `"type": "module"` (it is possible to put a separate `package.json` in the dir with esm output with `{ "type": "module" }` contents)
2. Imports are missing file extensions. Using `import ... from '<path>/<name>.js';` should work.
3. Optionally, `"module": "./dist/esm/index.js"` can be added alongside `"main": ...`
4. Optionally, file extensions should be `.mjs`

**Comment by anchan828** [comment]
I have released the revised version. Thank you for the PR!
https://www.npmjs.com/package/@anchan828/json-ast/v/2.1.185
