### ISSUE TITLE
Escaping not decoded during toJSON conversion

### ISSUE THREAD

**Issue by ankhzet** [anchan828/json-ast#1180]
When escaped string is encountered by native JSON parser (f.e. `"some \"inner\" qoutes and\ttabs"`), it is then stored in the resulting value without backslashes, with special sequences decoded (`some "inner" qoutes and	tabs`).

Because this library focuses on preserving original contents of nodes in the ast tree, it stores the values of strings in their original, escaped form (i.e. `some \"inner\" qoutes and\ttabs`)

As a consequence, when resulting ast tree is converted to json object with `toJSON` helper, the string values then contain escaped source strings, instead of decoded values:

```js
const doubleEscaped = JSON.stringify({ 'a\"\t\"c': 'a\"\t\"c' }); // {"a\"\t\"c":"a\"\t\"c"}

// native parse
const parsed = JSON.parse(doubleEscaped); // { 'a" "c': 'a" "c' } <- space between quotes here is actually a tabulation character

// toJSON
const jsoned = toJSON(parse(doubleEscaped)); // { 'a\"\t\"c': 'a\"\t\"c' } <- \t here is a '\' 't' characters sequence, not the tabulation character itself
```

**Comment by anchan828** [comment]
Released: https://www.npmjs.com/package/@anchan828/json-ast/v/2.2.0
Thanks!
